on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout
    - uses: actions/setup-java
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action
      with:
        flutter-version: '1.7.8+hotfix.4'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --debug --split-per-abi
    - name: Create a Release APK
      uses: ncipollo/release-action
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.BRIX_FLIX_TOKEN }}